# Generated by Django 5.0 on 2023-12-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersmodel',
            name='username',
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
