# Generated by Django 5.0 on 2023-12-29 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0004_alter_usersmodel_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TaskApp.tasks'),
        ),
    ]
